### ISSUE TITLE
panicked when run the command `clashctl`

### ISSUE THREAD

**Issue by XyLyXyRR** [George-Miao/clashctl#26]
Just panicked.

## info
OS: arch 5.15.72-1-lts
version: latest source
clash: 2022.8.26 premium

## how to reproduce
- `cargo +nightly install --git https://github.com/George-Miao/clashctl`
- `clashctl server add`
- `clashctl`

## logs
```log
thread '<unnamed>' panicked at 'Group member should be in all proxies', clashctl-tui/src/components/proxy/tree.rs:206:26
                                                                                                                        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                     fish: Job 1, 'clashctl' terminated by signal SIGABRT (Abort)
```

**Comment by George-Miao** [comment]
I'll look into this. Sorry didn't see the issue.

**Comment by George-Miao** [comment]
I think it's related to specific config. Is it possible that you share a copy of config with servers and credentials being redacted? Really appreciated. @XyLyXyRR

**Comment by XyLyXyRR** [comment]
```yaml
# Wed, Jan 11 12:21:31 PM

mixed-port: 10805
redir-port: 10806
allow-lan: true
mode: script
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ./clash-dashboard
routing-mark: 7777
auto-redir:
  enable: true
  auto-route: true

profile:
  tracing: true
  store-selected: true
  store-fake-ip: true
hosts:
  'lab.local.one': 172.20.0.2

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  use-hosts: true
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 127.0.0.1/8
      - 240.0.0.0/4
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 1.1.1.1
    # system
    - dhcp://system
    - dhcp://enp4s0
    - dhcp://wlp3s0
  fake-ip-filter:
    - "*.lan"
    - localhost
    # GitHub
    - "+.github.com"

    # Stun Services
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"

    # Google Voices
    - "lens.l.google.com"

    # Nintendo Switch STUN
    - "*.n.n.srv.nintendo.net"

    # PlayStation STUN
    - "+.stun.playstation.net"

    # XBox
    - "xbox.*.*.microsoft.com"
    - "*.*.xboxlive.com"

    # Microsoft Captive Portal
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"

    # bilibili
    - "+.hdslb.com"

    # Bilibili CDN
    - "*.mcdn.bilivideo.cn"
    - "*.mcdn.bilivideo.cn.lan"
    - "+.bilibili.com"
    - "+.bilivideo.com"

    # Windows Default LAN WorkGroup
    - "WORKGROUP"

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
```
